[package]
org= "ballerinax"
name= "microsoft.excel"
version= "1.0.1-SNAPSHOT"
license= ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["productivity/spreadsheets", "cost/free", "vendor/microsoft"]
repository = "https://github.com/ballerina-platform/module-ballerinax-microsoft.excel"
