[package]
org= "ballerinax"
name= "microsoft.excel"
version= "2.0.0"
license= ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["Productivity/Spreadsheets", "Cost/Free", "Vendor/Microsoft"]
repository = "https://github.com/ballerina-platform/module-ballerinax-microsoft.excel"
